#!/bin/sh

VIMRC_URL="https://raw.github.com/xsb/vimstamp/master/vimrc"
VIMRC="$HOME/.vimrc"
BACKUP="$HOME/.vimrc.bak"
CURL="$(which curl) -s"
if [ $? -ne 0 ]; then
	echo ">> curl command not found"
	exit 1
fi

if [ -f $VIMRC ]; then
	mv $VIMRC $BACKUP
	echo ">> Saved $VIMRC as $BACKUP"
fi

$CURL $VIMRC_URL > $VIMRC
echo ">> Updated $VIMRC"
